name: login_bloc_app
description: A Flutter application with BLoC state management.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.5
  
  # Models & Equality
  equatable: ^2.0.5
  
  # API Calls
  http: ^1.2.1
  
  # Form Validation
  formz: ^0.7.0
  
  # UI & Fonts
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.gif
